---
title: "final project"
output: html_document
date: "2023-11-20"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(forecast)
library(ggplot2)

data = read.csv("leatherjacket.csv")

data.ts = ts(data$Leather.jacket, start = c(2004, 1), 
             end = c(2023, 10), freq = 12)
autoplot(data.ts, ylab = "Search Volume")

```

Classical Decomposition
```{r}
seasonplot(data.ts, year.labels = T, col=rainbow(12))
data.lm = lm(data.ts~time(data.ts))
plot(data.ts)+abline(data.lm,col=2)
summary(data.lm)
Acf(data.lm$residuals, lag.max = 48)

data.lm2 = lm(data.ts~time(data.ts)+I(time(data.ts)^2))
data.lm2
summary(data.lm2)
Acf(data.lm2$residuals, lag.max = 48)

data.lm.seasonal = tslm(data.ts ~ trend + season)
autoplot(data.ts)+geom_line(aes(y=data.lm.seasonal$fitted.values),
                            col=6)
checkresiduals(data.lm.seasonal)
summary(data.lm.seasonal)
```

Naive forecast/Seasonal naive forecast
```{r}
n = length(data.ts)
stepAhead = 24
nTrain = n- stepAhead
train.ts = window(data.ts, end=c(start(data.ts)[1],nTrain))
valid.ts = window(data.ts, start=c(start(data.ts)[1],nTrain+1))

naive = naive(train.ts, h=24)
seasonal = snaive(train.ts,24)

accuracy(naive, valid.ts)
accuracy(seasonal,valid.ts)
checkresiduals(seasonal)

autoplot(train.ts, ylab = "Search Volume") + 
  autolayer(seasonal, series="Seasonal Naive", PI=F)+
#  autolayer(naive, series = "Naive", PI=F)+
  autolayer(valid.ts,series="Actual Data")
```

Moving Average
```{r}
library(zoo)
#Center Moving Average
ma.centered = ma(data.ts, order = 12)
autoplot(data.ts,ylab="Search Volume",col="black",series = "Observed")+
  autolayer(ma.centered, series = "Moving average", lwd =1.5)+
  scale_x_continuous(breaks=seq(from=2004,to=2023,2))

#Trailing Moving Average
ma.trailing = rollmean(data.ts, k=12, align="right")
autoplot(data.ts,ylab="Search Volume",col="black",series = "Observed")+
  autolayer(ma.centered, series = "Moving average", lwd =1.5)+
  autolayer(ma.trailing, series = "MA trailing", lwd =1.5)+
  scale_x_continuous(breaks=seq(from=2004,to=2023,2))

#Forecasting
nValid = 24
ma.trailing = rollmean(train.ts, k=12, align = "right")
pred = tail(ma.trailing,1)
ma.trailing.pred = ts (rep(pred,nValid), start = start(valid.ts),
                       frequency = frequency(valid.ts))
mean.valid = ts (rep(mean(valid.ts), nValid), 
                 start = start(valid.ts), 
                 frequency = frequency(valid.ts))

autoplot(data.ts,ylab="Search Volume",col="black",series = "Observed")+
  autolayer(ma.trailing.pred, series = "Predicted", lwd =1.5)+
  autolayer(mean.valid, series = "Average", lwd =1.5)+
  scale_x_continuous(breaks=seq(from=2004,to=2023,2))

accuracy(ma.trailing.pred, valid.ts)



#one-step-ahead rolling forecast
w=24
step=1
ma.trail.pred=rep(NA,nValid)

for(i in 1:nValid){
nTrain = length(data.ts) - nValid +(i-1)
train.ts = window(data.ts,
                  end=c(2004,nTrain))
ma.roll = rollmean(train.ts, k=w, align ="right")
ma.roll=tail(ma.roll,1)
ma.trail.pred[i]= ma.roll}

ma.pred.ts = ts(ma.trail.pred, start = start(valid.ts), frequency = frequency(valid.ts))


autoplot(valid.ts) + autolayer(ma.pred.ts, series="Short term")+ autolayer(ma.trailing.pred, series = "Long term")

accuracy(ma.pred.ts,valid.ts)
accuracy(ma.trailing.pred,valid.ts)
```

Differencing
```{r}
lag.1 = diff(data.ts, lag = 1)
autoplot(lag.1)
checkresiduals(lag.1)

#second difference
diff2.lag.1 = diff(lag.1, lag = 1)
autoplot(diff2.lag.1)
checkresiduals(diff2.lag.1)

#dtds
dt.ds = diff(lag.1, lag = 12)
autoplot(dt.ds)
checkresiduals(dt.ds)

#remove seasonal component from the original data
ds = diff(data.ts, lag = 12)
autoplot(ds)
checkresiduals(ds)
```

#Seasonal Exponential Smoothing
```{r}
#dnTrain = length(dt.ds) - nValid
#dtrain.ts = window(dt.ds, end = c(2005, dnTrain + 1)) 
#dvalid.ts = window(dt.ds, start = c(2005, dnTrain + 1 + 1))

#ses = ets(dtrain.ts, model = "ANA", alpha = 0.2)
#ses.pred = forecast.ets(ses, h = nValid, level = 0)
#autoplot(dvalid.ts) +
#  autolayer(ses.pred)

#ses optimal
#ses.opt = ets(dtrain.ts, model = "ANA")
#ses.opt

#ses.opt.pred = forecast.ets(ses.opt, h = nValid, level = 0)

#compare the accuracy for the two versions
#accuracy(ses.pred, dvalid.ts)
#accuracy(ses.opt.pred, dvalid.ts)


```


ANA
```{r}
nValid = 24
nTrain = length(data.ts) - nValid

train.ts = window(data.ts, end = c(2004,nTrain))
valid.ts = window(data.ts, start =c(2004, nTrain+1))

zzz = ets(train.ts, model = "ZZZ")
zzz.pred = forecast.ets (zzz, h = nValid, level =0)

accuracy(zzz.pred, valid.ts)
checkresiduals(zzz.pred)

autoplot(train.ts, ylab = "Search Volume") + 
  autolayer(zzz.pred, series="ANA", PI=F)+
  autolayer(valid.ts,series="Actual Data")
```


ARIMA
```{r}
Acf(data.ts, lag.max = 100)
Pacf(data.ts, lag.max = 60) 

Acf(diff(train.ts, 1), 60) 
#seasonal ACF is significant for 3 seasons only.
Pacf(diff(train.ts, 1), 60)

m1 = Arima(train.ts, order = c(1, 1, 1), 
           seasonal = list(order = c(1, 0, 0), period = 12))
summary(m1)

m1.p = forecast(m1, h = length(valid.ts))

autoplot(m1.p)

autoplot(valid.ts) +
  autolayer(m1.p$mean)

accuracy(m1.p, valid.ts)
checkresiduals(m1)

m2 = Arima(train.ts, order = c(1, 1, 0), 
           seasonal = list(order = c(1, 0, 0), period = 12))
summary(m2)

m3 = Arima(train.ts, order = c(0, 1, 1), 
           seasonal = list(order = c(1, 0, 0), period = 12))
summary(m3)


Acf(diff(diff(train.ts, 1),12), 60) 
#seasonal ACF is significant for 3 seasons only.
Pacf(diff(diff(train.ts, 1),12), 60)

# AR(1), MA(1), ARIMA(1,1)
m4 = Arima(train.ts, order = c(1, 1, 0), 
           seasonal = list(order = c(0, 1, 1), period = 12))
summary(m4)

m5 = Arima(train.ts, order = c(0, 1, 1), 
           seasonal = list(order = c(0, 1, 1), period = 12))
summary(m5)

m6 = Arima(train.ts, order = c(1, 1, 1), 
           seasonal = list(order = c(0, 1, 1), period = 12))
summary(m6)

m6.p = forecast(m6, h = length(valid.ts))

autoplot(m6.p, PI = F)

autoplot(valid.ts) +
  autolayer(m6.p$mean)

accuracy(m6.p, valid.ts)
checkresiduals(m6)

m7 = Arima(train.ts, order = c(1, 0, 1), 
           seasonal = list(order = c(1, 1, 1), period = 12))
summary(m7)

m7.p = forecast(m7, h = length(valid.ts))

autoplot(m7.p, PI = F)

autoplot(valid.ts) +
  autolayer(m7.p$mean)

autoplot(train.ts, ylab = "Search Volume") + 
  autolayer(m7.p$mean, series="ARIMA(1,0,1)(1,1,1)")+
  autolayer(valid.ts,series="Actual Data")

accuracy(m7.p, valid.ts)
checkresiduals(m7)

m7.p.2024 = forecast(m7, h = length(valid.ts) + 12)
m7.p.2024
autoplot(train.ts, main ="Future Prediction",
         ylab = "Search Volume") + 
  autolayer(m7.p.2024$mean, series="ARIMA(1,0,1)(1,1,1)")+
  autolayer(valid.ts,series="Actual Data")
```


Variables
```{r}
library(astsa)
library(tseries)
temp = read.csv("temperature_new.csv", header = T)
temp_ts = ts(temp$Temperature, start = c(2004, 1),
             end = c(2023, 10), frequency = 12)
cci = read.csv("CCI.csv", header = T)
cci_ts = ts(cci$Value, start = c(2004, 1),
            end = c(2023, 10), frequency = 12)
emp = read.csv("unemployment_new.csv", header = T)
emp_ts = ts(emp$Unemployment, start = c(2004, 1),
            end = c(2023, 10), frequency = 12)
precip = read.csv("precipitation_new.csv", header = T)
precip_ts = ts(precip$Precipitation, start = c(2004, 1),
               end = c(2023, 10), frequency = 12)

plot(temp_ts, main = "Temperature", xlab = "", ylab = "")
plot(cci_ts, main = "CCI", xlab = "", ylab = "")
plot(emp_ts, main = "Unemployment Rate", xlab = "", ylab = "")
plot(precip_ts, main = "Precipitation", xlab = "", ylab = "")

adf.test(temp_ts, alternative = "stationary", k = 0)
adf.test(cci_ts, alternative = "stationary", k = 0)
adf.test(emp_ts, alternative = "stationary", k = 0)
adf.test(precip_ts, alternative = "stationary", k = 0)

pairs(cbind(LeatherJacket = data.ts, Temperature = temp_ts, 
            CCI = cci_ts, UnemploymentRate = emp_ts,
            Precipitation = precip_ts))

cor(data.ts, temp_ts)
cor(data.ts, cci_ts)
cor(data.ts, emp_ts)
cor(data.ts, precip_ts)

lag2.plot(temp_ts, data.ts, 8)

lm1 = tslm(data.ts ~ trend + season)
lm2 = tslm(data.ts ~ trend + season + temp_ts)
lm3 = tslm(data.ts ~ trend + season + temp_ts + I(temp_ts^2))
#lm4 = tslm(data.ts ~ trend + temp_ts + I(temp_ts^2) + part.tr)
#model_test = lm(data.ts ~ temp_ts + cci_ts + emp_ts + precip_ts)
#library(car)
#vif(model_test)

summary(lm1)$adj.r.squared
summary(lm2)$adj.r.squared
summary(lm3)$adj.r.squared

accuracy(lm1$fitted.values, data.ts)
accuracy(lm2$fitted.values, data.ts)
accuracy(lm3$fitted.values, data.ts)

Ccf(data.ts, temp_ts, 26)

newdata = ts.intersect(data.ts, temp = temp_ts,
                       leadT1 = lag(temp_ts, -1),
                       leadT13 = lag(temp_ts, -13))
head(newdata, 2)
lm5 = tslm(data.ts ~ trend + temp + I(temp^2) + leadT1 +
            leadT13 , data = newdata)

summary(lm5)
accuracy(lm5$fitted.values, data.ts)
```

nnetar
```{r}
data.nnetar = nnetar(train.ts, repeats = 20, p = 1, P = 1,
                          size = 9)

data.nnetar.pred = forecast(data.nnetar, h = nValid)

accuracy(data.nnetar.pred, valid.ts)

autoplot(data.nnetar.pred) +
  autolayer(data.nnetar$fitted, series = "Fitted") +
  autolayer(valid.ts, series = "Actual")


data.nnetar.opt = nnetar(train.ts)


data.nnetar.opt.pred = forecast(data.nnetar.opt,
                                     h = nValid)
accuracy(data.nnetar.opt.pred, valid.ts)  
autoplot(data.nnetar.opt.pred) +
  autolayer(data.nnetar.opt$fitted, series = "Fitted") +
  autolayer(valid.ts, series = "Actual")
```


Final Model
```{r}
m_final = Arima(data.ts, order = c(1, 0, 1), 
           seasonal = list(order = c(1, 1, 1), period = 12))
summary(m_final)

m_final.p = forecast(m_final, h = 12)

autoplot(data.ts, ylab = "Search Volume") + 
  autolayer(m_final.p$mean, series="Forecasting")

m_final.p
```

